In [79]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss
    
    
net = simpleNet()
print(net.W)

x= np.array([0.6, 0.9])
p = net.predict(x)
print(p)
print(np.argmax(p))

t = np.array([0, 0, 1])
print(net.loss(x, t))

def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)



[[ 0.13276138  0.10284602 -0.04980232]
 [-0.68500463  1.46209966  1.48923959]]
[-0.53684734  1.37759731  1.31043424]
1
0.8007158061962937
[[ 0.04247569  0.28811983 -0.33059552]
 [ 0.06371353  0.43217975 -0.49589328]]
